[package]
name = "spectre"
version = "0.1.0"
authors = ["averysumner", "C34A"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
